#!/bin/bash

echo "start"
date

idf.py build
ssh saric@192.168.2.1 "cat /var/www/html/termbig/termbig.bin | md5sum"

md5sum build/term-big-3-eth.bin

scp build/term-big-3-eth.bin saric@192.168.2.1:/var/www/html/termbig/termbig.bin

mosquitto_pub -h 192.168.2.1 -t "/termbig-in/PUDA/bootloader" -m "0"

echo "done"
